const PORT: number = +process.env.PORT! || 8000;
const GAME_TICKER_MS: number = 100;
const CANVAS_WIDTH: number = 1400;
const CANVAS_HEIGHT: number = 750;
const SHIP_POSITION_Y: number = CANVAS_HEIGHT - 32;
const BULLET_SHOOT_POS_Y: number = SHIP_POSITION_Y;
const MIN_PLAYERS_TO_START_MATCH: number = 2;
const PHYSICS_WORLD_TIMESTEP: number = 1 / 16;
const PLAYER_VERTICAL_MOVEMENT_UPDATE_INTERVAL: number = 1000;
const PLAYER_VERTICAL_INCREMENT: number = 20;
const PLAYER_SCORE_INCREMENT: number = 5;

export {
  PORT,
  GAME_TICKER_MS,
  CANVAS_WIDTH,
  CANVAS_HEIGHT,
  SHIP_POSITION_Y,
  BULLET_SHOOT_POS_Y,
  MIN_PLAYERS_TO_START_MATCH,
  PHYSICS_WORLD_TIMESTEP,
  PLAYER_VERTICAL_MOVEMENT_UPDATE_INTERVAL,
  PLAYER_VERTICAL_INCREMENT,
  PLAYER_SCORE_INCREMENT,
};
