const PORT = process.env.PORT || 8000;
const GAME_TICKER_MS = 100;
const CANVAS_WIDTH = 1400;
const CANVAS_HEIGHT = 750;
const SHIP_POSITION_Y = CANVAS_HEIGHT - 32;
const BULLET_SHOOT_POS_Y = SHIP_POSITION_Y;
const MIN_PLAYERS_TO_START_MATCH = 2;
const PHYSICS_WORLD_TIMESTEP = 1 / 16;
const PLAYER_VERTICAL_MOVEMENT_UPDATE_INTERVAL = 1000;
const PLAYER_VERTICAL_INCREMENT = 20;
const PLAYER_SCORE_INCREMENT = 5;

module.exports = {
  PORT,
  GAME_TICKER_MS,
  CANVAS_WIDTH,
  CANVAS_HEIGHT,
  SHIP_POSITION_Y,
  BULLET_SHOOT_POS_Y,
  MIN_PLAYERS_TO_START_MATCH,
  PHYSICS_WORLD_TIMESTEP,
  PLAYER_VERTICAL_MOVEMENT_UPDATE_INTERVAL,
  PLAYER_VERTICAL_INCREMENT,
  PLAYER_SCORE_INCREMENT,
};